### PR TITLE
First stab at fixing #13: Scaling UI with device.

### PR DESCRIPTION
**Pull request by dglazkov**

### CODE REVIEW

**Comment by dglazkov** [comment]
Made a first pass. Not finished yet.

**Review by decompil3d — COMMENTED** [review]
Looks mostly good. My only concern is that background images are stripped in high contrast mode, so it would be better to leave the candidate icons as img elements.

**Comment by dglazkov** [comment]
Yeah, I got a little overeager there 😄 . Will put it back.

**Comment by dglazkov** [comment]
@JonathanKeslin ready for review.

**Pull request merged**
